# 5 Discussion

Hypothesis for London Underground ridership in this study assumed the impact of the COVID-19 pandemic would be long lasting and remain detectable from the ridership change years after the outbreak. The hypothesis expected Underground demand to recover faster in central London. It also expected commuting recovery in central London recovering slower than all-purpose travel represented by annualised ridership, since many work places adapted remote-working after the pandemic. Apparently, some findings in this study suggest otherwise. In this section, discussion will focus on the temporal pattern of London Underground ridership change before and after COVID-19, the spatial clustering condition of stations with similar recovery profiles, and the extent of impact COVID-19 had on commuting demands and overall demands.

## 5.1 Pre-pandemic underground ridership

To understand the extent of the COVID-19 pandemic’s disruption on London underground ridership, the context of underground usage trend needs to be clearly identified, which is shown in the line charts of ridership from 2017 to 2019 (Figure 1 and 2) in section 4.1. The results show relatively stable ridership pattern for both annualised and weekday commuting data. Even with 2017-2018 ridership inflated and 2019 data deflated due to different data definition, which would exaggerate the trend slightly, the trajectory of weekday commuting usage is still more stable than annualised trend. While more drastic pattern shifts occur in zone 7 to 9, it is worth noting that the number of stations in zone 7-9 is far less than other zones, at around 10% of the amount of stations in Zone 1, which makes the outcome more biased than central zones. As a result, we can still safely assume that ridership of stations in central zones were stable before the outbreak, though it is hard to determine if the demand was increasing or decreasing in general, with only two years of ridership data analysis.

Although designed by TfL directly to simplify ticketing, the fare zones of London Underground only identifies the central -peripheral distribution of stations, rather than reflecting the characteristics of the area. Studies explicitly examining how fare zones themselves influence Underground ridership remains limited, although one might expect the cost of travel in different zones to impact travel behaviours. Notably, Roth et al. (2011) analysed London’s public transport card flows, which implies complex demand patterns across zones, even if the direct role of zonal fare boundaries was not tested. Meanwhile, like many metropolis, London has a polycentric structure (Zhang et al., 2021) that attract more people in some centres than other areas, while the fare zones only show the distance from one station to the geographic centre of the city, which may explain anomalies such as the unusually high average pre-pandemic Underground ridership in Zone 2. Nonetheless, fare zones provide a useful scope for distinguishing inner and outer London ridership patterns before the pandemic, as stations within the 5 central zones all showed similar trends.

## 5.2 Commuting pattern shifts in post-pandemic time

Once again, grouping stations by fare zone showed a clear distribution of the recovery conditions for each station post-pandemic, as the boxplot of recovery rate shows (Figure 3 and 4). As expected, in 2021 the majority of Underground stations across London experienced a significant decrease in usage. In 2022 and 2023, annualised ridership had climbed to 70% of pre-pandemic levels, compared with less than 50% in 2021. However, contrary to the hypothesis, Underground commuting bounced back quickly after 2021. Weekday ridership, representing commuting patterns, showed more resilience to the pandemic, and in 2022 commuting ridership was already higher than 2019, reaching around 150% of the baseline. This result itself might not directly prove a diminishing of the pandemic’s disruption, since multiple factors can drive the increase of Underground usage. But when compared with annualised recovery, it is still likely that the impact of COVID-19 on commuting ridership in the London Underground is not as long-lasting as on the overall demand for this infrastructure. Moreover, contrary to the hypothesis, ridership of Zone 1 recovered more slowly than surrounding areas in both annualised and weekday ridership patterns, which might be a result of companies adopting remote working. However, a study conducted by Batty et al. (2020) during the pandemic in London showed that the mobility patterns of people working on-site were not significantly different from those of people who worked remotely, suggesting that mode of work may not directly impact commuting demand for public transport.

The outcomes of the k-means analysis provided another temporal scope to look at recovery. By setting the profiles of stagnant recovery, gradual recovery, and over-recovery, the overall change of each station from 2021 to 2023 could be seen. Stagnant recovery stations were concentrated in central London, which matches the trend already suggested by the boxplots: Underground ridership in central areas recovered slower than in outer areas (Murcio et al., 2023). Apart from this central cluster, other stations with similar recovery profiles seemed to be more line-specific than area-specific. This suggests the possibility of stations on the same line sharing similar recovery extent, which is not examined in this study, but grouping stations by their lines might help explaining some trends. 

It is worth noting that, considering the boxplots showed outlines, the process of categorising stations into 3 groups with K-means inevitably smoothed out some of the differences. This means stations in the same group may still have quite different recovery rates. Even so, the fact that stations with the same profile can be visually observed in clusters on the map made it reasonable to move on to formal spatial analysis to test whether recovery rates really form spatial clusters.

Taken together, the comparison between pre- and post-pandemic ridership changes indicate that the disruption and following rebound in Underground ridership cannot be explained as a continuation of pre-existing trend. The relatively stable underground usage sharp declined in 2021 and rapidly rebounded in 2022–23, demonstrates that the pandemic likely introduced a distinct break from prior trends.

## 5.3 Systematic spatial pattern of recovery rates

To examine if the recovery conditions of Underground stations in this study present spatial clustering patterns, the Global Moran’s I was tested first in order to find out if systematic clustering exists. As shown by the Global Moran’s I values in section 4.3 (Table 2 and 3), only recovery patterns in 2021 indicated significance in spatial clustering, and the observation applied for both annualised and weekday recovery. Different k-nearest values were also tested, yet the outcomes all fell in the same trend. Although no existing studies have explicitly suggested a k value for London transport, the result was enough to verify that, from the scope of Greater London, significant spatial clustering only appeared in 2021, the first year after the outbreak. To some extent, this result confirmed the finding in previous sections of temporal analysis, suggesting that comparing with the pre-pandemic baseline, the Underground demand in 2022 and 2023 showed little evidence of COVID-19 impact, from both temporal trajectory and spatial pattern, although more detailed analysis is needed to further confirm the opinion, which is discussed in the following sections.

## 5.4 Spatial clusters from Local Moran’s I

Temporally, both annualised and weekday LISA results showed the same trend: spatial clustering of stations with similar recovery profile drastically decreased after 2021. Spatially, comparing with the overall insignificant result from Global Moran’s I, Local Moran’s I still indicated clustering occurring across London in 2022 and 2023. The most persistent pattern was the Low-Low clusters occurring in central London area, across the three years in this study, for both annualised and weekday ridership groups. Since the Low-Low clusters only appeared in central London, it is safe to assume that from the perspective of underground station usage recovery, stations in inner London recovered slower over the post-pandemic years, and had lower recovery rate comparing with outer London area.

Compared with annualised ridership, the weekday commuting ridership recovery did not show significant different in spatial clustering, apart from in 2021 more High-High clusters could be observed in weekday than annualised recovery. However, some clusters appeared in the north-west side were outside of Greater London boundary. Despite the line service being operated by TfL, the scattered stations outside London in Zone 7-9 might not provide solid proof for recovery analysis. High-High clusters in east London appeared to follow along the line, showing similar pattern to the K-Means grouping result (Figure 6), which suggests from the spatial angle that it might be worth analysing the recovery rates of stations from the perspective of Underground line.

In general, this result fits the findings of existing London post-pandemic transport studies. As discussed in section 2.2, Spatially, both Murcio et al. (2023) and Batty et al. (2020) observed significant drop in commuting in central London. Statistically, the survey did by Bansal et al. (2022) showed sharp decrease in overall commuting trips. Moreover, according to Trasberg and Cheshire (2021), central London serves the function as a hub for office jobs in finance and professional service sector, which experienced largest activity decrease in London. 

However, the majority of datasets used in these researches were collected in 2020-2021, which might not align with findings for year 2022 and 2023. Murcio et al. used O-D flow data with hourly time intervals from 2022, and their findings suggest that by October 2022, commuting ridership in London Underground was still lower than pre-pandemic levels, which is opposite to the findings of commuting ridership over-recovering since 2021 in this study. This might be a result of different dataset nature and granularity. In this study, recovery rate is calculated based on annual level entry/exit data with no origin or destination. In finer datasets, definition for commuting can be set with more details, as morning/evening rush periods and origin/destination between home and work both serve as indicators in distinguishing commuting trips. With different information availability in datasets for defining commuting, it is possible results of studies in contrary of each other.

## 5.5 Robustness of Local Moran’s I 

Even though the recovery profile in this study is different from some previous findings, the spatial clustering of areas with low transport recovery across different study and methods is relatively consistent, with central London being the major cluster of low recovery rates. Still, the robustness of Local Moran’s I experiment in this study is examined. As shown in section 4.5, Figure 13 represented the annualised recovery when k = 3 and 8; Figure 14 showed weekday commuting clustering with different k values. As expected, when k value is relatively large, as 8 in this test, setting the closest 8 stations for each station as neighbours. This loosens the selection of neighbours, so in both ridership groups more significant spatial clustering was observed. Under this condition, central London’s Low-Low clustering involved a larger amount of stations, and High-High clustering became more significant. 

High-High cluster appeared in the western boundary of Greater London, which was observed in the majority of conditions and persisted in 2023 when very few clusters remained detectable. In 2021, High-High clusters in weekday commuting recovery is much more detectable than annualised recovery, and later years. Similar to the outcome when k=5, here the line-based clustering was emphasised. Upon further research, the cluster in west London was Heathrow Airport, which served both business and leisure purposes post-pandemic as London’s largest airport. Meanwhile, the segment in east London where high recovery clusters was a shared track between District Line and Metropolitan Line. Despite the test itself did not identify line membership, this clustering suggested the two Underground line likely shared similar recovery profile. Although without examining line-level recovery rate, this conclusion remains as an assumption.

It is possible that the “true” spatial pattern of station recovery is revealed when even higher k values are tested. However, considering the dataset in this study contains the 270 stations of London Underground only, defining eight stations as neighbours for each station when k=8 might already exaggerates the pattern. With no prior research specified a suitable k selection in London, the range of spatial clustering itself can not be determined with the outcomes of this study. Nonetheless, the robustness test when k = 3 and 8 revealed similar spatial clustering patterns to the default experiment when k=5, which validated the spatial pattern of low Underground ridership recovery post-pandemic clustered in central London, high recovery cluster tends to vary under different conditions, and does not shown significantly spatial pattern. 

## 5.6 Getis-Ord Gi*statistics for hot spots and cold spots

Lastly, Getis-Ord Gi* method was used to validate Local Moran’s I clustering with a different local statistic. As expected, the overall pattern of hot spots and cold spots detected in both annualised (Figure 15) and weekday (Figure 16) recovery showed similar location of High-High and Low-Low clusters in Local Moran’s I test. This further confirmed the validity of low recovery area and high recovery area detected using Local Moran’s I. However, in 2023, both annualised and weekday Gi* results showed slightly more hot spots than the previous year, which contradicts the diminishing pattern of clustering showed in Local Moran’s I outcomes, although cold spots followed the same trend. Considering the fact that in Local Moran’s I outcomes, especially when k=5, a clear spatial pattern of High-High cluster was never found, it is possible that the hot spots appeared in Gi* results in 2023 held low significance in terms of explaining spatial pattern. Moreover, since both default experiment of Local Moran’s I and Gi* used the k value of 5, Gi* might return different distribution of hot spots if different k values were tested for Gi* as well. As a result, Gi* validated that low recovery or cold spot were clustered in central London area, but no significant high recovery or hot spot was identified, apart from stations connecting the Heathrow Airport, which does not reflect the common usage of Underground. While spatial pattern remained similar overall under different sensitivity, the validity of k value itself is not verified in this study.

After the Global and Local Moran’s I experiment, with the robustness check using different k values, and the Gi* hot/cold spots as complementary evidence, we can say that both annualised mixed purpose ridership and weekday commuting ridership show similar spatial pattern, which is significant in 2021, but becomes less clustered since 2022, indicating station level recovery grows more random. Still, compared with annualised group, weekday ridership shows clearer high recovery pattern, indicating high recovery cluster might be associated with their Underground line profile. The clearer commuting recovery pattern also suggests that, the weekday selection of Monday to Thursday in this study might indeed represent the commuting profile, while annualised mixed purpose trips likely dilute the spatial clustering pattern at station level. With the most consistent low recovery cluster, we can safely say that recovery in mixed purpose and commuting purpose Underground ridership in central London experienced lower degree of recovery than surrounding areas, commuting recovery shows stronger low recovery clustering than mixed purpose demand, suggests that central London has weaker resilience towards the COVID-19 pandemic than the rest of Greater London, which might be a result of the commuting focused Underground demand of the area.